added repository dispatch trigger in github workflow to allow schematic to trigger dca deployment
Sage-Bionetworks/data_curator pull request #447
Opened 2022-12-01 17:52 UTC by linglp

Related to the issue here: https://github.com/Sage-Bionetworks/schematic/issues/1026
Hopefully could give it a try :)

2022-12-01 19:12 UTC, rrchai commented
@linglp Thanks for testing the repo dispatch. It looks like the deployment failed, but feel free to re-run the workflow - it might be just one-time issue.

Since the destination of deployment in our current workflow file is still depended on the branch name, two places are also needed to be considered:
- [here](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/.github/workflows/shinyapps_deploy.yml#L51-L67) is where the `main/develop` branch of `schematic` is going to clone
- [here](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/.github/workflows/shinyapps_deploy.yml#L103-L112) is codes to determine which instance (prod/staging//testing1) is being deployed. The develop branch is only 

I think using repo dispatch to trigger opening a PR might be a way, like:
the request will be sent when the `develop` branch of `schematic` updates -> open a pr based on `develop` of dca -> opening a PR will auto trigger the deployment to `testing1` instance which will use `develop` branch of `schematic`

2022-12-01 19:41 UTC, linglp commented
> @linglp Thanks for testing the repo dispatch. It looks like the deployment failed, but feel free to re-run the workflow - it might be just one-time issue.
> 
> Since the destination of deployment in our current workflow file is still depended on the branch name, two places are also needed to be considered:
> 
> * [here](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/.github/workflows/shinyapps_deploy.yml#L51-L67) is where the `main/develop` branch of `schematic` is going to clone
> * [here](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/.github/workflows/shinyapps_deploy.yml#L103-L112) is codes to determine which instance (prod/staging/testing1) is being deployed.
> 
> I think using repo dispatch to trigger opening a PR might be an alternative way (also developers can review if the latest develop of schematic passes the workflow), it will be like:
> 
> 1. the request will be sent when the `develop` branch of `schematic` updates
> 2. open a pr compared to `develop` of dca
> 3. opening a PR will auto trigger the deployment to [testing1](https://sagebio.shinyapps.io/data_curator-testing1/) instance which will use `develop` branch of `schematic`

Thanks @rrchai ! I tried running the workflow again and it worked. Could you allow github action to trigger opening PRs? I don't have the permission to do it. You could do it via repository's settings: Actions > General > Workflow permissions.

2022-12-02 19:53 UTC, linglp commented
Related to PR from schematic: https://github.com/Sage-Bionetworks/schematic/pull/1044

2022-12-07 19:44 UTC, rrchai requested changes

2022-12-07 19:44 UTC, rrchai commented on .github/workflows/open-PR.yml
> +        run: date +%s > mock.txt
I suggest to update another file, like `schematic_config.yml`

2022-12-07 19:49 UTC, rrchai commented
Thanks @linglp. I would suggest to add one property ("version") in `schematic_config.yml` and update the version each event. It can be also used to update from `release` changes from schematic as well. 

I made the attempt with [this wl](https://github.com/rrchai/rong-flow-test/blob/main/.github/workflows/ci.yaml) using [yaml-update-action](https://github.com/fjogeleit/yaml-update-action), which can update the value of yaml file and create a pr. The example of created PR is [here](https://github.com/rrchai/rong-flow-test/pull/4).

2022-12-08 18:45 UTC, linglp commented
> Thanks @linglp. Instead of updating `report.txt`, I would suggest to update `schematic_config.yml` (you can add "version" property in the file). So the version of schematic used is stored in the config file, which we could use for the app. Also, it can be used for `release` updates of schematic - just need to replace with the version tag.
> 
> I made the attempt with [this wl](https://github.com/rrchai/rong-flow-test/blob/main/.github/workflows/ci.yaml) using [yaml-update-action](https://github.com/fjogeleit/yaml-update-action), which can update the value of yaml file and create a pr. The example of created PR is [here](https://github.com/rrchai/rong-flow-test/pull/4). Let me know if you have any questions.

Thanks @rrchai ! Your suggestion makes sense. I have updated the PR to use the workflows that you recommended. One thing that I am not sure is how to "switch" between "develop" and "main" branch based on if the release tag exists or not by using the `targetBranch` parameter. Let me know if you have any thought.

2022-12-08 18:46 UTC, linglp commented on .github/workflows/open-PR.yml
> +        if: ${{ env.RELEASE_VERSION != '' }}
if release tag does not exist, trigger a PR to merge into the `develop` branch

2022-12-08 18:47 UTC, linglp commented on .github/workflows/open-PR.yml
> +        if: ${{ env.RELEASE_VERSION == '' }}
if the release tag does not exist, trigger a PR to update the develop branch

2022-12-21 16:15 UTC, linglp commented on .github/workflows/open-PR.yml
> +          targetBranch: main
change to "targetBranch: develop"

2022-12-21 16:22 UTC, rrchai commented on .github/workflows/open-PR.yml
> +            }
remove this part - duplicated

2022-12-21 16:23 UTC, rrchai approved these changes
LGTM! Just one comment

2023-01-05 21:56 UTC, rrchai commented
Merging this PR to `develop`

2023-01-05 21:56 UTC, merged